# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Code Ahoy
tagline:          ''
description:      'Articles on Software and Human Factors.'
url:              http://codeahoy.com
baseurl:          /

# Social Media
twitter:        codeahoy
linkedin:       umansoor
facebook:       codeahoy
facebook_id:    194256054293519


author:
  name:           'Umer Mansoor'
  url:            https://twitter.com/codeahoy

name: Code Ahoy
description: Articles on Software and Human Factors.
url: http://codeahoy.com


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/umermansoor

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
