# Dependencies
#markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            CodeAhoy
tagline:          'Technology. People. Imagination.'
description:      'Technology. People. Imagination.'
url:              https://codeahoy.com
baseurl:          https://codeahoy.com/

# Social Media
twitter:        codeahoy
linkedin:       umansoor
facebook:       codeahoy
facebook_id:    194256054293519

gems:
  - jekyll-redirect-from

author:
  name:           'Umer Mansoor'
  url:            https://twitter.com/codeahoy

name: CodeAhoy
description: Technology. People. Imagination.
url: https://codeahoy.com


paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/umermansoor

gems:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb
